/**
 * Bot Configuration System
 *
 * This file defines the configuration interface for different bots
 * and provides the list of bots to run in multi-bot Elo evaluation mode.
 */

export interface BotConfig {
  /** Unique identifier for the bot */
  id: string;

  /** Human-readable name for display */
  name: string;

  /** Description of what makes this bot different */
  description: string;

  /** Model to use for note writing */
  noteModel: string;

  /** Model to use for scoring filters (optional, defaults to claude-3.5-sonnet) */
  filterModel?: string;

  /** Score thresholds (optional, uses defaults if not specified) */
  thresholds?: {
    verifiableFact?: number; // default: 0.5
    url?: number; // default: 0.5
    positive?: number; // default: 0.5
    disagreement?: number; // default: 0.5
    helpfulness?: number; // default: 0.5
    xApiScore?: number; // default: -0.25
  };

  /** Custom prompt modifications (optional) */
  promptModifiers?: {
    /** Additional instructions to append to note-writing prompt */
    noteWritingInstructions?: string;
  };

  /** Whether this bot is enabled for multi-bot runs */
  enabled: boolean;
}

/**
 * Default thresholds used when not specified in bot config
 */
export const DEFAULT_THRESHOLDS = {
  verifiableFact: 0.5,
  url: 0.5,
  positive: 0.5,
  disagreement: 0.5,
  helpfulness: 0.5,
  xApiScore: -0.25,
};

/**
 * Get thresholds for a bot, merging with defaults
 */
export function getBotThresholds(bot: BotConfig): typeof DEFAULT_THRESHOLDS {
  return {
    ...DEFAULT_THRESHOLDS,
    ...bot.thresholds,
  };
}

/**
 * Bot configurations for multi-bot Elo evaluation
 *
 * Add new bots here to test different configurations.
 * The Elo system will compare notes generated by these bots.
 */
export const BOT_CONFIGS: BotConfig[] = [
  {
    id: "baseline-sonnet4",
    name: "Baseline Sonnet 4",
    description: "The current production configuration using Claude Sonnet 4",
    noteModel: "anthropic/claude-sonnet-4",
    enabled: true,
  },
  {
    id: "opus-45",
    name: "Opus 4.5",
    description: "Uses Claude Opus 4.5 for potentially higher quality notes",
    noteModel: "anthropic/claude-opus-4-5-20251101",
    enabled: true,
  },
  {
    id: "sonnet-35",
    name: "Sonnet 3.5",
    description: "Uses Claude 3.5 Sonnet for faster, cheaper notes",
    noteModel: "anthropic/claude-3.5-sonnet",
    enabled: true,
  },
  {
    id: "strict-thresholds",
    name: "Strict Thresholds",
    description: "Higher thresholds for more conservative note selection",
    noteModel: "anthropic/claude-sonnet-4",
    thresholds: {
      helpfulness: 0.7,
      disagreement: 0.6,
      positive: 0.6,
    },
    enabled: false, // Disabled by default - enable to test
  },
  {
    id: "lenient-thresholds",
    name: "Lenient Thresholds",
    description: "Lower thresholds to post more notes",
    noteModel: "anthropic/claude-sonnet-4",
    thresholds: {
      helpfulness: 0.4,
      disagreement: 0.4,
      positive: 0.4,
    },
    enabled: false, // Disabled by default - enable to test
  },
];

/**
 * Get all enabled bots
 */
export function getEnabledBots(): BotConfig[] {
  return BOT_CONFIGS.filter((bot) => bot.enabled);
}

/**
 * Get a bot by ID
 */
export function getBotById(id: string): BotConfig | undefined {
  return BOT_CONFIGS.find((bot) => bot.id === id);
}
