name: Create Notes Routine

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour at minute 0
  workflow_dispatch:
  push:
    branches:
      - main
      - 'staging:*'

jobs:
  fetch-and-submit:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Add timeout to prevent infinite hanging
    env:
      # X API OAuth 1.0a credentials
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
      X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
      X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
      # OpenRouter API key for AI models
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      # Airtable credentials for logging
      AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run create notes routine script
        run: bun run src/scripts/createNotesRoutine.ts
